const tracks = [
  {file:"music/Avec_Toi_spotdown_org.mp3", cover:"music/covers/Avec_Toi_spotdown_org.jpg", title:"Avec Toi", artist:"OBOY", album:"OMEGA"},
  {file:"music/Jusqu_au_dernier_gramme_spotdown_org.mp3", cover:"music/covers/Jusqu_au_dernier_gramme_spotdown_org.jpg", title:"Jusqu'au dernier gramme", artist:"PNL", album:"Dans la légende"},
  {file:"music/À_tes_côtés_spotdown_org.mp3", cover:"music/covers/À_tes_côtés_spotdown_org.jpg", title:"À tes côtés", artist:"Djadja & Dinaz", album:"À tes côtés"},
  {file:"music/Princesse_de_Babel__SABR__spotdown_org.mp3", cover:"music/covers/Princesse_de_Babel__SABR__spotdown_org.jpg", title:"Princesse de Babel (SABR)", artist:"Zamdane", album:"Unknown Album"},
  {file:"music/Ailleurs_spotdown_org.mp3", cover:"music/covers/Ailleurs_spotdown_org.jpg", title:"Ailleurs", artist:"Josman", album:"J.000.$"},
  {file:"music/La_course_spotdown_org.mp3", cover:"music/covers/La_course_spotdown_org.jpg", title:"La course", artist:"Bouss", album:"Et si j'échoue ??"},
  {file:"music/Daruma_spotdown_org.mp3", cover:"music/covers/Daruma_spotdown_org.jpg", title:"Daruma", artist:"Népal", album:"Adios Bahamas"},
  {file:"music/Cohiba_spotdown_org.mp3", cover:"music/covers/Cohiba_spotdown_org.jpg", title:"Cohiba", artist:"Josman", album:"J.000.$"},
  {file:"music/Amsterdam_spotdown_org.mp3", cover:"music/covers/Amsterdam_spotdown_org.jpg", title:"Amsterdam", artist:"Moha La Squale", album:"Amsterdam"},
  {file:"music/Mi_Amor_spotdown_org.mp3", cover:"music/covers/Mi_Amor_spotdown_org.jpg", title:"Mi Amor", artist:"Hamza", album:"H-24"},
  {file:"music/Rare_spotdown_org.mp3", cover:"music/covers/Rare_spotdown_org.jpg", title:"Rare", artist:"VEN1", album:"Rare"},
  {file:"music/J_béou_spotdown_org.mp3", cover:"music/covers/J_béou_spotdown_org.jpg", title:"J'béou", artist:"Bouss", album:"Et si j'échoue ??"},
  {file:"music/Jeu_spotdown_org.mp3", cover:"music/covers/Jeu_spotdown_org.jpg", title:"Jeu", artist:"Favé", album:"Pleins Phares"},
  {file:"music/JAMAIS_TOI_spotdown_org.mp3", cover:"music/covers/JAMAIS_TOI_spotdown_org.jpg", title:"JAMAIS TOI", artist:"R2", album:"JAMAIS TOI"},
  {file:"music/Vent_de_l_est_spotdown_org.mp3", cover:"music/covers/Vent_de_l_est_spotdown_org.jpg", title:"Vent de l'est", artist:"Laylow", album:".RAW-Z"},
  {file:"music/SAINT-LAURENT_spotdown_org.mp3", cover:"music/covers/SAINT-LAURENT_spotdown_org.jpg", title:"SAINT-LAURENT", artist:"Moji x Sboy", album:"SAINT-LAURENT"},
  {file:"music/ON_THE_MAP_spotdown_org.mp3", cover:"music/covers/ON_THE_MAP_spotdown_org.jpg", title:"ON THE MAP", artist:"T3llz", album:"Unknown Album"},
  {file:"music/Naha_spotdown_org.mp3", cover:"music/covers/Naha_spotdown_org.jpg", title:"Naha", artist:"PNL", album:"Dans la légende"},
  {file:"music/Croire_spotdown_org.mp3", cover:"music/covers/Croire_spotdown_org.jpg", title:"Croire", artist:"Djadja & Dinaz", album:"Drôle de mentalité"},
  {file:"music/Faf_spotdown_org.mp3", cover:"music/covers/Faf_spotdown_org.jpg", title:"Faf", artist:"Werenoi", album:"Pyramide 2"},
  {file:"music/Le_bruit_et_le_silence_spotdown_org.mp3", cover:"music/covers/Le_bruit_et_le_silence_spotdown_org.jpg", title:"Le bruit et le silence", artist:"NeS", album:"Des pieds et des mains"},
  {file:"music/Crossfader_spotdown_org.mp3", cover:"music/covers/Crossfader_spotdown_org.jpg", title:"Crossfader", artist:"Népal", album:"Adios Bahamas"},
  {file:"music/Rose_spotdown_org.mp3", cover:"music/covers/Rose_spotdown_org.jpg", title:"Rose", artist:"Ninho", album:"Comme prévu"},
  {file:"music/HINATA_spotdown_org.mp3", cover:"music/covers/HINATA_spotdown_org.jpg", title:"HINATA", artist:"TIF", album:"1.6"},
  {file:"music/Bambina_spotdown_org.mp3", cover:"music/covers/Bambina_spotdown_org.jpg", title:"Bambina", artist:"PNL", album:"Dans la légende"},
  {file:"music/DEHØRS_spotdown_org.mp3", cover:"music/covers/DEHØRS_spotdown_org.jpg", title:"DEHØRS", artist:"Bekar", album:"Mirasierra"},
  {file:"music/SUBLIME_spotdown_org.mp3", cover:"music/covers/SUBLIME_spotdown_org.jpg", title:"SUBLIME", artist:"disiz", album:"L'Amour"},
  {file:"music/Bad_Day__SABR__spotdown_org.mp3", cover:"music/covers/Bad_Day__SABR__spotdown_org.jpg", title:"Bad Day (SABR)", artist:"Zamdane", album:"Unknown Album"},
  {file:"music/Ma_dope_spotdown_org.mp3", cover:"music/covers/Ma_dope_spotdown_org.jpg", title:"Ma dope", artist:"Nekfeu, S.Pri Noir", album:"Feu"},
  {file:"music/Luna_spotdown_org.mp3", cover:"music/covers/Luna_spotdown_org.jpg", title:"Luna", artist:"Moha La Squale", album:"Bendero"},
  {file:"music/Elles_ont_trop_joué_avec_mon_coeur_spotdown_org.mp3", cover:"music/covers/Elles_ont_trop_joué_avec_mon_coeur_spotdown_org.jpg", title:"Elles ont trop joué avec mon coeur", artist:"Jok'air", album:"VI République (Version finale)"},
  {file:"music/Prioritaire_spotdown_org.mp3", cover:"music/covers/Prioritaire_spotdown_org.jpg", title:"Prioritaire", artist:"Maes", album:"Les derniers salopards"},
  {file:"music/Jolie__feat__Ninho__spotdown_org.mp3", cover:"music/covers/Jolie__feat__Ninho__spotdown_org.jpg", title:"Jolie (feat. Ninho)", artist:"GAULOIS, Ninho", album:"Jolie (feat. Ninho)"},
  {file:"music/Quand_tout_s_enflamme_spotdown_org.mp3", cover:"music/covers/Quand_tout_s_enflamme_spotdown_org.jpg", title:"Quand tout s'enflamme", artist:"Georgio, PLK", album:"Années Sauvages"},
  {file:"music/Hakayet_spotdown_org.mp3", cover:"music/covers/Hakayet_spotdown_org.jpg", title:"Hakayet", artist:"VEN1", album:"Nichen"},
  {file:"music/Solitaire_spotdown_org.mp3", cover:"music/covers/Solitaire_spotdown_org.jpg", title:"Solitaire", artist:"Werenoi", album:"Telegram"},
  {file:"music/Luz_de_Luna_spotdown_org.mp3", cover:"music/covers/Luz_de_Luna_spotdown_org.jpg", title:"Luz de Luna", artist:"PNL", album:"Dans la légende"}
];
